#!/bin/sh

minify() {
	cd "$1"

	[ ! -d .tmp ] && mkdir .tmp

	for f in $(ls); do
		if [ -f $f ]; then
			cp $f .tmp/$f

			cat .tmp/$f | tr -d '\n' | tr -d '\t' | sed -E "s/\{2,}//g" > $f
		fi
	done

	cd -
}

minify _layouts
minify _layouts/indexes
minify _layouts/indexes/category
minify _layouts/partials
