#!/bin/sh

unminify() {
	cd "$1"

	for f in $(ls); do
		if [ -f $f ]; then
			cp .tmp/$f $f
			continue
		fi
	done

	rm -r .tmp/

	cd -
}

unminify _layouts
unminify _layouts/indexes
unminify _layouts/indexes/category
unminify _layouts/partials
